In [4]:
import pandas as pd
import numpy as np
from sklearn. feature_extraction. text import CountVectorizer
from sklearn. model_selection import train_test_split
from sklearn. tree import DecisionTreeClassifier
import nltk
import re
nltk. download('stopwords')
from nltk. corpus import stopwords


[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/chamodyaavishka/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


In [5]:
#Stopwords Initialization
stopword=set(stopwords.words('english'))

#Stemmer Initialization
stemmer = nltk. SnowballStemmer("english")

In [6]:
#load the data set &  preview the data
data = pd. read_csv("labeled_data.csv")

print(data. head())


   Unnamed: 0  count  hate_speech  offensive_language  neither  class  \
0           0      3            0                   0        3      2   
1           1      3            0                   3        0      1   
2           2      3            0                   3        0      1   
3           3      3            0                   2        1      1   
4           4      6            0                   6        0      1   

                                               tweet  
0  !!! RT @mayasolovely: As a woman you shouldn't...  
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...  
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...  
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...  
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...  


In [7]:
#Label Mapping & Data selection
data["labels"] = data["class"]. map({0: "Hate Speech", 1: "Offensive Speech", 2: "No Hate and Offensive Speech"})
data = data[["tweet", "labels"]]
print(data. head())

                                               tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...   
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                         labels  
0  No Hate and Offensive Speech  
1              Offensive Speech  
2              Offensive Speech  
3              Offensive Speech  
4              Offensive Speech  


In [8]:

data = data[['tweet', 'labels']]
data.head()
     

tweet  \
0  !!! RT @mayasolovely: As a woman you shouldn't...   
1  !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2  !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3  !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4  !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   

                         labels  
0  No Hate and Offensive Speech  
1              Offensive Speech  
2              Offensive Speech  
3              Offensive Speech  
4              Offensive Speech

In [9]:
data.info

<bound method DataFrame.info of                                                    tweet  \
0      !!! RT @mayasolovely: As a woman you shouldn't...   
1      !!!!! RT @mleew17: boy dats cold...tyga dwn ba...   
2      !!!!!!! RT @UrKindOfBrand Dawg!!!! RT @80sbaby...   
3      !!!!!!!!! RT @C_G_Anderson: @viva_based she lo...   
4      !!!!!!!!!!!!! RT @ShenikaRoberts: The shit you...   
...                                                  ...   
24778  you's a muthaf***in lie &#8220;@LifeAsKing: @2...   
24779  you've gone and broke the wrong heart baby, an...   
24780  young buck wanna eat!!.. dat nigguh like I ain...   
24781              youu got wild bitches tellin you lies   
24782  ~~Ruffled | Ntac Eileen Dahlia - Beautiful col...   

                             labels  
0      No Hate and Offensive Speech  
1                  Offensive Speech  
2                  Offensive Speech  
3                  Offensive Speech  
4                  Offensive Speech  
...                

In [10]:
#data Cleaning
def clean (text):
 text = str (text). lower()#lowercase
 text = re. sub('[.?]', '', text) 
 text = re. sub('https?://\S+|www.\S+', '', text)
 text = re. sub('<.?>+', '', text)
 text = re. sub('\n', '', text)
 text = re. sub('\w\d\w', '', text)
 text = [word for word in text.split(' ') if word not in stopword]
 text=" ". join(text)
 text = [stemmer. stem(word) for word in text. split(' ')]#stemming
 text=" ". join(text)
 return text
data["tweet"] = data["tweet"]. apply(clean)
     

<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:8: SyntaxWarning: invalid escape sequence '\w'
<>:5: SyntaxWarning: invalid escape sequence '\S'
<>:8: SyntaxWarning: invalid escape sequence '\w'
/var/folders/58/g_5xrc8j1zdckrn739h9xr2m0000gn/T/ipykernel_60293/3840919798.py:5: SyntaxWarning: invalid escape sequence '\S'
  text = re. sub('https?://\S+|www.\S+', '', text)
/var/folders/58/g_5xrc8j1zdckrn739h9xr2m0000gn/T/ipykernel_60293/3840919798.py:8: SyntaxWarning: invalid escape sequence '\w'
  text = re. sub('\w\d\w', '', text)


In [11]:
x = np. array(data["tweet"])
y = np. array(data["labels"])

# Vectorize the data (Converting text data in to matrix of token count)
cv = CountVectorizer()
X = cv. fit_transform(x)

# Splitting the Data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
     


In [12]:
#Model building & Training the model
model = DecisionTreeClassifier()
model. fit(X_train,y_train)

DecisionTreeClassifier()

In [13]:
#Testing the model
y_pred = model. predict (X_test)
y_pred
     


array(['Offensive Speech', 'Offensive Speech',
       'No Hate and Offensive Speech', ..., 'Offensive Speech',
       'Offensive Speech', 'Offensive Speech'], dtype=object)

In [14]:
#Accuracy Score of the model
from sklearn. metrics import accuracy_score
print (accuracy_score (y_test,y_pred))

0.8845824672942902


In [15]:
inp = "You are nice"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['No Hate and Offensive Speech']


In [16]:
inp = "Yo yoo"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['No Hate and Offensive Speech']


In [17]:
inp = "bitch"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['Offensive Speech']


In [18]:
inp = "you so beautiful"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))

['No Hate and Offensive Speech']


In [19]:
inp = "Fuck you"
inp = cv. transform([inp]). toarray()
print(model. predict(inp))
     

['Offensive Speech']


In [20]:
# Confusion Matrix
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test, y_pred))

[[ 172   53  240]
 [  30 1209  140]
 [ 274  207 5854]]


In [21]:
# Precision
from sklearn.metrics import precision_score
print(precision_score(y_test, y_pred, average=None))

[0.36134454 0.82300885 0.93904395]


In [22]:
# Accuracy
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.8845824672942902


In [23]:
# Recall
from sklearn.metrics import recall_score
print(recall_score(y_test, y_pred, average=None))

[0.36989247 0.87672226 0.92407261]


In [24]:
# f1 score
from sklearn.metrics import f1_score
print(f1_score(y_test, y_pred, average=None))

[0.36556854 0.84901685 0.93149813]


In [33]:
import joblib

# Let's say your model is stored in `model` and the vectorizer in `cv`
joblib.dump(model, '/Users/chamodyaavishka/Desktop/ML projects/Hate-Speech_detection/model.joblib')
joblib.dump(cv, '/Users/chamodyaavishka/Desktop/ML projects/Hate-Speech_detection/vectorizer.joblib')


['/Users/chamodyaavishka/Desktop/ML projects/Hate-Speech_detection/vectorizer.joblib']